import 'dart:io';

import 'package:flutter/material.dart';
import 'package:multi_language_pdf/multi_language_pdf.dart';
import 'package:open_filex/open_filex.dart';
import 'package:share_plus/share_plus.dart';

void main() {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'multi_language_pdf Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorSchemeSeed: Colors.indigo,
        useMaterial3: true,
      ),
      home: const HomeScreen(),
    );
  }
}

// ---------------------------------------------------------------------------
// Build the demo PdfDocument — uses every widget in the package,
// and includes content in English, Hindi, Russian, Japanese, and Chinese.
// ---------------------------------------------------------------------------
PdfDocument buildDocument() {
  return PdfDocument(
    pageConfig: PdfPageConfig.a4Portrait(
      margin: const PdfEdgeInsets.all(32),
    ),
    children: [
      // ── 1. HEADER STACK ────────────────────────────────────────────────
      // Demonstrates PdfStack + PdfPositioned + PdfContainer + PdfText
      PdfStack(
        children: [
          PdfPositioned(
            top: 0,
            left: 0,
            child: PdfContainer(
              width: 730,
              height: 90,
              color: PdfColor.fromHex('#3949AB'),
              border: PdfBorder(
                  color: PdfColor.transparent, width: 0, radius: 10),
            ),
          ),
          PdfPositioned(
            top: 14,
            left: 24,
            child: PdfColumn(
              crossAxisAlignment: PdfCrossAxisAlignment.start,
              children: [
                PdfText(
                  'Multilingual PDF Report',
                  fontSize: 24,
                  bold: true,
                  color: PdfColor(255, 255, 255),
                ),
                PdfText(
                  'Generated by multi_language_pdf  •  English · हिन्दी · Русский · 日本語 · 中文',
                  fontSize: 11,
                  color: PdfColor(200, 210, 255),
                ),
              ],
            ),
          ),
          PdfPositioned(
            top: 20,
            right: 20,
            child: PdfIcon(
              Icons.picture_as_pdf,
              size: 48,
              color: PdfColor(255, 255, 255),
            ),
          ),
        ],
      ),

      PdfSizedBox(height: 20),

      // ── 2. META ROW ─────────────────────────────────────────────────────
      // Demonstrates PdfRow + PdfRichText + PdfIcon (inline)
      PdfRow(
        mainAxisAlignment: PdfMainAxisAlignment.spaceBetween,
        crossAxisAlignment: PdfCrossAxisAlignment.center,
        children: [
          PdfRichText(
            spans: [
              PdfTextSpan('Date: ', bold: true, fontSize: 12),
              PdfTextSpan('April 3, 2026',
                  fontSize: 12, color: PdfColor.fromHex('#555555')),
            ],
          ),
          PdfRichText(
            spans: [
              PdfTextSpan('Category: ', bold: true, fontSize: 12),
              PdfTextSpan('Language & Technology',
                  fontSize: 12, color: PdfColor.fromHex('#3949AB')),
            ],
          ),
          PdfRow(
            gap: 4,
            crossAxisAlignment: PdfCrossAxisAlignment.center,
            children: [
              PdfIcon(Icons.check_circle,
                  size: 14, color: PdfColor.fromHex('#4CAF50')),
              PdfText('Verified',
                  fontSize: 12, color: PdfColor.fromHex('#4CAF50')),
            ],
          ),
        ],
      ),

      PdfSizedBox(height: 8),
      PdfDivider(color: PdfColor.fromHex('#C5CAE9'), thickness: 2),
      PdfSizedBox(height: 14),

      // ── 3. INTRO CARD ───────────────────────────────────────────────────
      // Demonstrates PdfCard + PdfPadding + PdfRichText
      PdfCard(
        elevation: 2,
        borderRadius: 10,
        padding: const PdfEdgeInsets.all(16),
        child: PdfPadding(
          padding: const PdfEdgeInsets.only(left: 4),
          child: PdfRichText(
            spans: [
              PdfTextSpan('About this document:  ',
                  bold: true, fontSize: 13),
              PdfTextSpan(
                'This PDF demonstrates every widget in the multi_language_pdf package. '
                'It renders content in five scripts simultaneously: Latin (English), '
                'Devanagari (Hindi), Cyrillic (Russian), Hiragana/Katakana (Japanese), '
                'and Han characters (Chinese). All text is rendered natively by the '
                'browser engine inside the hidden WebView — no per-language font '
                'embedding required.',
                fontSize: 12,
                color: PdfColor.fromHex('#333333'),
              ),
            ],
          ),
        ),
      ),

      PdfSizedBox(height: 18),

      // ── 4. SECTION TITLE ────────────────────────────────────────────────
      PdfRow(
        gap: 8,
        crossAxisAlignment: PdfCrossAxisAlignment.center,
        children: [
          PdfIcon(Icons.language, size: 18,
              color: PdfColor.fromHex('#3949AB')),
          PdfText('Greetings in Five Languages',
              fontSize: 16,
              bold: true,
              color: PdfColor.fromHex('#3949AB')),
        ],
      ),

      PdfSizedBox(height: 10),

      // ── 5. MAIN TABLE ───────────────────────────────────────────────────
      // Demonstrates PdfTable + PdfTableColumn + PdfTableRow
      PdfTable(
        columns: [
          PdfTableColumn(
              label: 'Language', flex: 2, textAlign: PdfTextAlign.left),
          PdfTableColumn(
              label: 'Hello', flex: 2, textAlign: PdfTextAlign.center),
          PdfTableColumn(
              label: 'Thank You', flex: 2, textAlign: PdfTextAlign.center),
          PdfTableColumn(
              label: 'Good Morning',
              flex: 3,
              textAlign: PdfTextAlign.center),
          PdfTableColumn(
              label: 'Welcome', flex: 2, textAlign: PdfTextAlign.center),
        ],
        rows: [
          PdfTableRow(cells: [
            'English',
            'Hello',
            'Thank you',
            'Good morning',
            'Welcome'
          ]),
          PdfTableRow(cells: [
            'Hindi',
            'नमस्ते',
            'धन्यवाद',
            'सुप्रभात',
            'स्वागत है'
          ]),
          PdfTableRow(cells: [
            'Russian',
            'Привет',
            'Спасибо',
            'Доброе утро',
            'Добро пожаловать'
          ]),
          PdfTableRow(
            cells: [
              'Japanese',
              'こんにちは',
              'ありがとう',
              'おはようございます',
              'ようこそ'
            ],
            highlight: true,
          ),
          PdfTableRow(cells: [
            'Chinese',
            '你好',
            '谢谢',
            '早上好',
            '欢迎'
          ]),
        ],
        headerStyle: PdfTextStyle(
            bold: true,
            color: PdfColor(255, 255, 255),
            fontSize: 13),
        headerBackground: PdfColor.fromHex('#3949AB'),
        rowAlternateColor: PdfColor.fromHex('#EEF0FF'),
        border: PdfBorder(
            color: PdfColor.fromHex('#9FA8DA'), width: 1, radius: 0),
      ),

      PdfSizedBox(height: 20),

      // ── 6. TWO COLUMN CARDS ─────────────────────────────────────────────
      // Demonstrates PdfRow + PdfColumn + PdfContainer + PdfListView
      PdfRow(
        gap: 12,
        crossAxisAlignment: PdfCrossAxisAlignment.start,
        children: [
          // Left column — language fun facts
          PdfColumn(
            crossAxisAlignment: PdfCrossAxisAlignment.stretch,
            children: [
              PdfContainer(
                color: PdfColor.fromHex('#E8EAF6'),
                padding: const PdfEdgeInsets.all(12),
                border: PdfBorder(
                    color: PdfColor.fromHex('#9FA8DA'), width: 1, radius: 8),
                child: PdfColumn(
                  crossAxisAlignment: PdfCrossAxisAlignment.start,
                  children: [
                    PdfRow(
                      gap: 6,
                      children: [
                        PdfIcon(Icons.info_outline,
                            size: 14,
                            color: PdfColor.fromHex('#3949AB')),
                        PdfText('Language Facts',
                            fontSize: 13,
                            bold: true,
                            color: PdfColor.fromHex('#3949AB')),
                      ],
                    ),
                    PdfSizedBox(height: 8),
                    PdfListView(
                      gap: 6,
                      children: [
                        _factRow('English — 1.5 billion speakers'),
                        _factRow('Hindi — 600 million+ speakers'),
                        _factRow('Russian — 260 million speakers'),
                        _factRow('Japanese — 125 million speakers'),
                        _factRow('Chinese — 1.3 billion+ speakers'),
                      ],
                    ),
                  ],
                ),
              ),
            ],
          ),

          // Right column — package features checklist
          PdfColumn(
            crossAxisAlignment: PdfCrossAxisAlignment.stretch,
            children: [
              PdfCard(
                elevation: 1,
                borderRadius: 8,
                color: PdfColor(255, 255, 255),
                padding: const PdfEdgeInsets.all(12),
                child: PdfColumn(
                  crossAxisAlignment: PdfCrossAxisAlignment.start,
                  children: [
                    PdfRow(
                      gap: 6,
                      children: [
                        PdfIcon(Icons.check_box,
                            size: 14,
                            color: PdfColor.fromHex('#4CAF50')),
                        PdfText('Package Capabilities',
                            fontSize: 13,
                            bold: true,
                            color: PdfColor.fromHex('#2E7D32')),
                      ],
                    ),
                    PdfSizedBox(height: 8),
                    PdfListView(
                      gap: 6,
                      children: [
                        _checkRow('Flutter-inspired DSL'),
                        _checkRow('Zero state-manager dependency'),
                        _checkRow('Semantic pagination (no mid-row cuts)'),
                        _checkRow('Optional PDF preview widget'),
                        _checkRow('30-second timeout with error callback'),
                      ],
                    ),
                  ],
                ),
              ),
            ],
          ),
        ],
      ),

      PdfSizedBox(height: 20),

      // ── 7. MULTILINGUAL PHRASES SECTION ────────────────────────────────
      PdfRow(
        gap: 8,
        crossAxisAlignment: PdfCrossAxisAlignment.center,
        children: [
          PdfIcon(Icons.translate,
              size: 18, color: PdfColor.fromHex('#E91E63')),
          PdfText('Common Phrases',
              fontSize: 16,
              bold: true,
              color: PdfColor.fromHex('#E91E63')),
        ],
      ),

      PdfSizedBox(height: 10),

      // Demonstrates PdfContainer with colored backgrounds per language
      PdfColumn(
        children: [
          _languageBlock(
            langLabel: 'English',
            color: PdfColor.fromHex('#E3F2FD'),
            borderColor: PdfColor.fromHex('#1565C0'),
            phrases: [
              'The quick brown fox jumps over the lazy dog.',
              '"Technology knows no borders." — A universal truth.',
            ],
          ),
          PdfSizedBox(height: 8),
          _languageBlock(
            langLabel: 'Hindi — हिन्दी',
            color: PdfColor.fromHex('#FFF3E0'),
            borderColor: PdfColor.fromHex('#E65100'),
            phrases: [
              'यह पैकेज एक साथ कई भाषाओं में पीडीएफ बनाता है।',
              'तकनीक किसी भी भाषा की बाधा को पार कर सकती है।',
            ],
          ),
          PdfSizedBox(height: 8),
          _languageBlock(
            langLabel: 'Russian — Русский',
            color: PdfColor.fromHex('#F3E5F5'),
            borderColor: PdfColor.fromHex('#6A1B9A'),
            phrases: [
              'Этот пакет создаёт PDF-файлы на нескольких языках одновременно.',
              'Технологии объединяют людей по всему миру.',
            ],
          ),
          PdfSizedBox(height: 8),
          _languageBlock(
            langLabel: 'Japanese — 日本語',
            color: PdfColor.fromHex('#FCE4EC'),
            borderColor: PdfColor.fromHex('#880E4F'),
            phrases: [
              'このパッケージは複数の言語で同時にPDFを作成します。',
              'テクノロジーは世界中の人々をつなげます。',
            ],
          ),
          PdfSizedBox(height: 8),
          _languageBlock(
            langLabel: 'Chinese — 中文',
            color: PdfColor.fromHex('#E8F5E9'),
            borderColor: PdfColor.fromHex('#1B5E20'),
            phrases: [
              '该软件包可以同时生成多种语言的PDF文件。',
              '技术将世界各地的人们联系在一起。',
            ],
          ),
        ],
      ),

      PdfSizedBox(height: 20),

      // ── 8. NUMBERS TABLE ────────────────────────────────────────────────
      PdfRow(
        gap: 8,
        crossAxisAlignment: PdfCrossAxisAlignment.center,
        children: [
          PdfIcon(Icons.pin,
              size: 18, color: PdfColor.fromHex('#00897B')),
          PdfText('Numbers 1–5 in Each Language',
              fontSize: 16,
              bold: true,
              color: PdfColor.fromHex('#00897B')),
        ],
      ),

      PdfSizedBox(height: 10),

      PdfTable(
        columns: [
          PdfTableColumn(
              label: '#', flex: 1, textAlign: PdfTextAlign.center),
          PdfTableColumn(
              label: 'English', flex: 2, textAlign: PdfTextAlign.center),
          PdfTableColumn(
              label: 'Hindi', flex: 2, textAlign: PdfTextAlign.center),
          PdfTableColumn(
              label: 'Russian', flex: 2, textAlign: PdfTextAlign.center),
          PdfTableColumn(
              label: 'Japanese', flex: 2, textAlign: PdfTextAlign.center),
          PdfTableColumn(
              label: 'Chinese', flex: 2, textAlign: PdfTextAlign.center),
        ],
        rows: [
          PdfTableRow(
              cells: ['1', 'One', 'एक', 'Один', 'ichi (一)', 'Yi (一)']),
          PdfTableRow(
              cells: ['2', 'Two', 'दो', 'Два', 'ni (二)', 'Er (二)']),
          PdfTableRow(
              cells: ['3', 'Three', 'तीन', 'Три', 'san (三)', 'San (三)']),
          PdfTableRow(
              cells: ['4', 'Four', 'चार', 'Четыре', 'shi (四)', 'Si (四)']),
          PdfTableRow(
              cells: ['5', 'Five', 'पाँच', 'Пять', 'go (五)', 'Wu (五)']),
        ],
        headerStyle: PdfTextStyle(
            bold: true,
            color: PdfColor(255, 255, 255),
            fontSize: 12),
        headerBackground: PdfColor.fromHex('#00897B'),
        rowAlternateColor: PdfColor.fromHex('#E0F2F1'),
        border:
            PdfBorder(color: PdfColor.fromHex('#80CBC4'), width: 1),
      ),

      PdfSizedBox(height: 20),

      // ── 9. NETWORK IMAGE ────────────────────────────────────────────────
      // Demonstrates PdfImage.network
      PdfRow(
        gap: 8,
        crossAxisAlignment: PdfCrossAxisAlignment.center,
        children: [
          PdfIcon(Icons.image,
              size: 18, color: PdfColor.fromHex('#F57C00')),
          PdfText('Image Support (PdfImage.network)',
              fontSize: 16,
              bold: true,
              color: PdfColor.fromHex('#F57C00')),
        ],
      ),

      PdfSizedBox(height: 10),

      PdfCard(
        elevation: 1,
        borderRadius: 8,
        padding: const PdfEdgeInsets.all(12),
        child: PdfColumn(
          crossAxisAlignment: PdfCrossAxisAlignment.center,
          children: [
            PdfImage.network(
              'https://picsum.photos/seed/multilang/600/200',
              width: 600,
              height: 200,
            ),
            PdfSizedBox(height: 8),
            PdfText(
              'Network image loaded at generation time via PdfImage.network()',
              fontSize: 11,
              italic: true,
              color: PdfColor.fromHex('#757575'),
              textAlign: PdfTextAlign.center,
            ),
          ],
        ),
      ),

      PdfSizedBox(height: 20),

      // ── 10. FOOTER ──────────────────────────────────────────────────────
      PdfDivider(color: PdfColor.fromHex('#C5CAE9'), thickness: 1),
      PdfSizedBox(height: 10),

      PdfRow(
        mainAxisAlignment: PdfMainAxisAlignment.spaceBetween,
        crossAxisAlignment: PdfCrossAxisAlignment.center,
        children: [
          PdfRichText(
            spans: [
              PdfTextSpan('Generated by ',
                  fontSize: 11, color: PdfColor.fromHex('#757575')),
              PdfTextSpan('multi_language_pdf',
                  fontSize: 11,
                  bold: true,
                  color: PdfColor.fromHex('#3949AB')),
              PdfTextSpan(' package',
                  fontSize: 11, color: PdfColor.fromHex('#757575')),
            ],
          ),
          PdfRow(
            gap: 4,
            crossAxisAlignment: PdfCrossAxisAlignment.center,
            children: [
              PdfIcon(Icons.star, size: 12,
                  color: PdfColor.fromHex('#FFC107')),
              PdfIcon(Icons.star, size: 12,
                  color: PdfColor.fromHex('#FFC107')),
              PdfIcon(Icons.star, size: 12,
                  color: PdfColor.fromHex('#FFC107')),
              PdfText('  pub.dev/packages/multi_language_pdf',
                  fontSize: 11, color: PdfColor.fromHex('#757575')),
            ],
          ),
        ],
      ),
    ],
  );
}

// Helper — bullet row for fact lists
PdfWidget _factRow(String text) {
  return PdfRow(
    gap: 6,
    crossAxisAlignment: PdfCrossAxisAlignment.center,
    children: [
      PdfIcon(Icons.circle, size: 8, color: PdfColor.fromHex('#3949AB')),
      PdfText(text, fontSize: 11, color: PdfColor.fromHex('#333333')),
    ],
  );
}

// Helper — checkmark row for feature list
PdfWidget _checkRow(String text) {
  return PdfRow(
    gap: 6,
    crossAxisAlignment: PdfCrossAxisAlignment.center,
    children: [
      PdfIcon(Icons.check_circle_outline,
          size: 12, color: PdfColor.fromHex('#4CAF50')),
      PdfText(text, fontSize: 11, color: PdfColor.fromHex('#333333')),
    ],
  );
}

// Helper — colored language block
PdfWidget _languageBlock({
  required String langLabel,
  required PdfColor color,
  required PdfColor borderColor,
  required List<String> phrases,
}) {
  return PdfContainer(
    color: color,
    padding: const PdfEdgeInsets.all(12),
    border: PdfBorder(color: borderColor, width: 1, radius: 8),
    child: PdfColumn(
      crossAxisAlignment: PdfCrossAxisAlignment.start,
      children: [
        PdfText(langLabel,
            fontSize: 13, bold: true, color: borderColor),
        PdfSizedBox(height: 6),
        ...phrases.map(
          (p) => PdfPadding(
            padding: const PdfEdgeInsets.only(left: 12, bottom: 4),
            child: PdfText(p,
                fontSize: 12, color: PdfColor.fromHex('#333333')),
          ),
        ),
      ],
    ),
  );
}

// ---------------------------------------------------------------------------
// Home Screen
// ---------------------------------------------------------------------------
class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  bool _generating = false;
  int _currentPage = 0;
  int _totalPages = 0;

  late final PdfDocument _document;

  @override
  void initState() {
    super.initState();
    _document = buildDocument();
  }

  void _generate() {
    setState(() {
      _generating = true;
      _currentPage = 0;
      _totalPages = 0;
    });

    PdfGenerator.generate(
      document: _document,
      fileName: 'multilang_demo',
      onProgress: (page, total) {
        setState(() {
          _currentPage = page;
          _totalPages = total;
        });
      },
      onSuccess: (File file) {
        setState(() => _generating = false);
        _showSuccessDialog(file);
      },
      onError: (Object error) {
        setState(() => _generating = false);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error: $error'),
            backgroundColor: Colors.red,
          ),
        );
      },
    );
  }

  void _showSuccessDialog(File file) {
    showDialog<void>(
      context: context,
      builder: (ctx) => AlertDialog(
        icon:
            const Icon(Icons.check_circle, color: Colors.green, size: 48),
        title: const Text('PDF Generated'),
        content: Text(
          'Saved to:\n${file.path}',
          style: const TextStyle(fontSize: 12),
        ),
        actions: [
          TextButton(
            onPressed: () {
              Navigator.pop(ctx);
              OpenFilex.open(file.path);
            },
            child: const Text('Open'),
          ),
          FilledButton.icon(
            onPressed: () {
              Navigator.pop(ctx);
              SharePlus.instance.share(
                ShareParams(
                  files: [XFile(file.path)],
                  text: 'Multilingual PDF demo — multi_language_pdf',
                ),
              );
            },
            icon: const Icon(Icons.share),
            label: const Text('Share'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return PdfGeneratorScope(child: Scaffold(
      appBar: AppBar(
        title: const Text('multi_language_pdf Demo'),
        centerTitle: true,
        backgroundColor: const Color(0xFF3949AB),
        foregroundColor: Colors.white,
        actions: [
          IconButton(
            icon: const Icon(Icons.info_outline),
            tooltip: 'About',
            onPressed: () {
              showAboutDialog(
                context: context,
                applicationName: 'multi_language_pdf Demo',
                applicationVersion: '1.0.0',
                children: const [
                  Text(
                    'Demonstrates every widget in the multi_language_pdf '
                    'package with content in English, Hindi, Russian, '
                    'Japanese, and Chinese.',
                  ),
                ],
              );
            },
          ),
        ],
      ),
      body: Stack(
        children: [
          // Preview fills the screen
          PdfPreviewWidget(
            document: _document,
            loadingWidget: const Center(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  CircularProgressIndicator(),
                  SizedBox(height: 12),
                  Text('Rendering preview…'),
                ],
              ),
            ),
          ),

          // Generation overlay
          if (_generating)
            Container(
              color: Colors.black54,
              child: Center(
                child: Card(
                  margin:
                      const EdgeInsets.symmetric(horizontal: 40),
                  child: Padding(
                    padding: const EdgeInsets.all(24),
                    child: Column(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        const CircularProgressIndicator(),
                        const SizedBox(height: 16),
                        const Text(
                          'Generating PDF…',
                          style: TextStyle(
                              fontSize: 16,
                              fontWeight: FontWeight.bold),
                        ),
                        if (_totalPages > 0) ...[
                          const SizedBox(height: 8),
                          Text(
                            'Page $_currentPage of $_totalPages',
                            style:
                                const TextStyle(color: Colors.grey),
                          ),
                          const SizedBox(height: 8),
                          LinearProgressIndicator(
                            value: _currentPage / _totalPages,
                          ),
                        ],
                      ],
                    ),
                  ),
                ),
              ),
            ),
        ],
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _generating ? null : _generate,
        backgroundColor:
            _generating ? Colors.grey : const Color(0xFF3949AB),
        foregroundColor: Colors.white,
        icon: const Icon(Icons.picture_as_pdf),
        label: const Text('Generate PDF'),
      ),
    ));
  }
}
